-- Active: 1729487978852@@127.0.0.1@5432@readverse
insert into category (id, name, parent)
values (1, 'Arts & Photography', null),
       (2, 'Biographies & Memoirs', null),
       (3, 'Business & Money', null),
       (4, 'Calendars', null),
       (5, 'Children''s Books', null),
       (6, 'Comics & Graphic Novels', null),
       (7, 'Computers & Technology', null),
       (8, 'Cookbooks, Food & Wine', null),
       (9, 'Crafts, Hobbies & Home', null),
       (10, 'Christian Books & Bibles', null),
       (11, 'Engineering & Transportation', null),
       (12, 'Health, Fitness & Dieting', null),
       (13, 'History', null),
       (14, 'Humor & Entertainment', null),
       (15, 'Law', null),
       (16, 'Literature & Fiction', null),
       (17, 'Medical Books', null),
       (18, 'Mystery, Thriller & Suspense', null),
       (19, 'Parenting & Relationships', null),
       (20, 'Politics & Social Sciences', null),
       (21, 'Reference', null),
       (22, 'Religion & Spirituality', null),
       (23, 'Romance', null),
       (24, 'Science & Math', null),
       (25, 'Science Fiction & Fantasy', null),
       (26, 'Self-Help', null),
       (27, 'Sports & Outdoors', null),
       (28, 'Teen & Young Adult', null),
       (29, 'Test Preparation', null),
       (30, 'Travel', null),
       (31, 'LGBTQ+', null),
       (32, 'Education & Teaching', null);